### ISSUE TITLE
i get errros when i use pixivpy-async running on wl2-kali and win11

### ISSUE THREAD

**Issue by ev11ccaatt** [Mikubill/pixivpy-async#26]
win11:
login_web() get a wrong
![image](https://user-images.githubusercontent.com/70800641/156328692-a504d11f-3be5-4086-8306-eb4108b85469.png)

wls2-kali
`Traceback (most recent call last):
  File "/mnt/c/Users/Administrator/Desktop/test.py", line 5, in <module>
    from pixivpy_async import *
  File "/usr/local/lib/python3.9/dist-packages/pixivpy_async/__init__.py", line 6, in <module>
    from .aapi import AppPixivAPI
  File "/usr/local/lib/python3.9/dist-packages/pixivpy_async/aapi.py", line 2, in <module>
    from .bapi import BasePixivAPI
  File "/usr/local/lib/python3.9/dist-packages/pixivpy_async/bapi.py", line 9, in <module>
    from .net import Net
  File "/usr/local/lib/python3.9/dist-packages/pixivpy_async/net.py", line 1, in <module>
    import aiohttp
  File "/usr/lib/python3/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/lib/python3/dist-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/lib/python3/dist-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/lib/python3/dist-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/lib/python3/dist-packages/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str`

**Comment by Mikubill** [comment]
I can't reproduce it with v1.2.14 locally. Maybe something about the network or the server? Using an incorrect version of aiohttp may also lead to this error. (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000680)
